version: "3"
services:
  mongo:
    image: mongo
    volumes:
      - ./data:/data/db
    restart: always
    ports:
      - "27017:27017"
  web:
    build: .
    volumes:
      - ./:/usr/src/app/
    depends_on:
      - mongo
    ports:
      - "3000:3000"
    links:
      - mongo
