version: "3"
services:
  redis:
    image: redis:alpine
    ports:
     - "6379:6379"
    volumes:
      - redis-data:/data
  web:
    build: .
    volumes:
      - ./:/usr/src/app/
    depends_on:
      - redis
    ports:
      - "3000:3000"

volumes:
  redis-data:
