version: "3"
services:
  redis:
    image: redis:alpine
    volumes:
      - redis-data:/data
  web:
    build: .
    volumes:
      - ./:/usr/src/app/
    depends_on:
      - redis
    ports:
      - "3000:3000"
    links:
      - redis

volumes:
  redis-data:
